(function () {
    const config = window.SITE_CONFIG;
    if (!config) return;

    // Content is generated by build.js; runtime code only adds interactions.
    document.querySelectorAll('.faq-question').forEach(function (button, index) {
        const answer = button.nextElementSibling;
        answer.id = `faq-answer-${index}`;
        button.setAttribute('aria-controls', answer.id);
        button.setAttribute('aria-expanded', 'false');
        answer.hidden = true;
        button.addEventListener('click', function () {
            const open = button.getAttribute('aria-expanded') !== 'true';
            button.setAttribute('aria-expanded', String(open));
            answer.hidden = !open;
            button.parentElement.classList.toggle('open', open);
        });
    });

    const toy = document.getElementById('catToy');
    if (!toy) return;
    if (!config.catToy.enabled) { toy.hidden = true; return; }
    const ball = toy.querySelector('.toy-ball');
    const string = toy.querySelector('.toy-string');
    const physics = window.ToyPhysics;
    const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');
    const LENGTH = 160;
    let state = { angle: 0, velocity: 0 };
    let frame = 0;
    let lastTime = 0;
    let previous = null;

    function render() {
        const x = 160 + Math.sin(state.angle) * LENGTH;
        const y = Math.cos(state.angle) * LENGTH;
        string.setAttribute('d', `M 160 0 L ${x} ${y}`);
        ball.style.left = `${x / 3.2}%`;
        ball.style.top = `${y / 2.2}%`;
        ball.style.transform = `translate(-50%, -50%) rotate(${-state.angle * 120}deg)`;
    }
    function tick(time) {
        frame = 0;
        if (document.hidden) return;
        state = physics.advance(state, (time - lastTime) / 1000);
        lastTime = time;
        render();
        if (state.angle || state.velocity) frame = requestAnimationFrame(tick);
    }
    function start() {
        if (frame || document.hidden) return;
        if (reducedMotion.matches) { state = { angle: 0, velocity: 0 }; render(); return; }
        lastTime = performance.now();
        frame = requestAnimationFrame(tick);
    }
    function stop() { cancelAnimationFrame(frame); frame = 0; }
    function brush(x, y, time) {
        const point = { x, y, time };
        if (previous && time - previous.time < 150 && !reducedMotion.matches) {
            const rect = ball.getBoundingClientRect();
            const impulse = physics.brushImpulse(previous, point, {
                x: rect.left + rect.width / 2,
                y: rect.top + rect.height / 2,
                radius: rect.width / 2 + 16
            });
            if (impulse) {
                state.velocity = physics.clamp(state.velocity + impulse, -7, 7);
                start();
            }
        }
        previous = point;
    }
    document.addEventListener('pointermove', function (event) {
        if (event.pointerType === 'touch') return;
        brush(event.clientX, event.clientY, performance.now());
    }, { passive: true });
    // Observe touches without capturing them or preventing normal page scrolling.
    document.addEventListener('touchstart', function (event) {
        const touch = event.touches[0];
        previous = { x: touch.clientX, y: touch.clientY, time: performance.now() };
    }, { passive: true });
    document.addEventListener('touchmove', function (event) {
        const touch = event.touches[0];
        if (touch) brush(touch.clientX, touch.clientY, performance.now());
    }, { passive: true });
    document.addEventListener('touchend', function () { previous = null; }, { passive: true });
    document.addEventListener('visibilitychange', function () { if (document.hidden) stop(); else start(); });
    reducedMotion.addEventListener('change', function () { stop(); start(); });
    render();
})();
